### PR TITLE
Fixing multi.mset and a pre-existing unit test.

### PR DESCRIPTION
**Pull request by jpodwys**
* transactions.js: `Multi.mset()` internally calls `.set()` but did not have scope access to it. Passing `self` instead of `null` fixes this.
* hash.js: Made `.hmget()` return `null` for absent keys rather than `undefined`.

@yamsellem

### CODE REVIEW

**Comment by jpodwys** [comment]
@yamsellem I'm hoping you'll have time to look at this today or tomorrow. I'd like to use your repo in the event that this gets merged.

**Comment by jpodwys** [comment]
Thank you!

**Comment by yamsellem** [comment]
Included in 0.2.16 release (and tag).

This library is a legacy to me, I've extended it a year ago and released it because the original library was releasing at a very slow peace. I've tested it again today running make and had to fix the should dependency to 3.x to make them all run (the include method has been deleted from the should library).

May I ask why you chose this library in particular?

**Comment by jpodwys** [comment]
Thanks for the quick response. I'm using [mock-redis-client](https://github.com/darrylwest/mock-redis-client) which extends your repo. I needed this fixed so I figured I'd fix mock-redis-client's dependency rather than forking both repos. When I looked at your repo last week it said the most recent commit was by you 7 days prior, so it seemed like you were still maintaining it.

Is there a complete redis mock elsewhere that you recommend I use?

**Comment by yamsellem** [comment]
@komachi has pointed out [redis-js](https://github.com/wilkenstein/redis-mock-js) to me in [a previous pull request](https://github.com/yamsellem/node-redis-mock/pull/6) which seems to handle every needs.

Don't hesitate to try it and give your impressions on it here ;-).

**Comment by jpodwys** [comment]
Perhaps you should note at the top of your readme that this is deprecated and send people to redis-js.

**Comment by yamsellem** [comment]
Yep, you're right ;-).
I've used this fork a year ago for personal use (_and because the forked repo was frozen_).

I was surprise to regularly receive pull requests.
I don't know if this repo has any use any more.
Maybe your confirmation on the use of [redis-js](https://github.com/wilkenstein/redis-mock-js) will help on the matter.

**Comment by komachi** [comment]
I found also [fakeredis](https://github.com/hdachev/fakeredis) which seems to be most popular. You can mention them both in README.

**Comment by yamsellem** [comment]
Marked as `no maintainer`.
Thanks for your help on the matter.

**Pull request merged**
